version: '3.7'

services:
  web:
    container_name: production_sng_api
    image: production_sng_api
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    # command: gunicorn name_string_api:app -b 0.0.0.0:5000
    # volumes:
    #   - static_volume:/home/app/web/staticfiles
    #   - media_volume:/home/app/web/mediafiles
    # expose:
    #   - 5000
    networks:
      - sng_network
    ports:
      - 5000:5000
    # env_file:
    #   - ./.env.prod
    # depends_on:
    #   - db
  nginx:
    container_name: production_nginx
    image: production_nginx
    build: ./nginx
    # volumes:
    #   - static_volume:/home/app/web/staticfiles
    #   - media_volume:/home/app/web/mediafiles
    networks:
      - sng_network
    ports:
      - 80:80
    depends_on:
      - web

networks:
  sng_network:

# volumes:
#   postgres_data:
#   static_volume:
#   media_volume: