Vagrant.configure(2) do |config|
  config.vm.box = "genebean/centos-7-docker-ce"
  config.vm.synced_folder ".", "/repo/sng/"
  config.vm.network "private_network", ip: "192.168.10.101"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 2
    vb.name = "sng-centos-7"
  end
  config.vm.provision "shell", inline: <<-SHELL
    mkdir -p /usr/local/lib/docker/cli-plugins
    curl -SL https://github.com/docker/compose/releases/download/v2.13.0/docker-compose-linux-x86_64 -o /usr/local/lib/docker/cli-plugins/docker-compose
    chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
    docker compose version
    cd /repo/sng/
    sudo /usr/local/lib/docker/cli-plugins/docker-compose -f docker-compose.yml up -d --build
  SHELL
end
